ALTER TABLE products
  ADD COLUMN IF NOT EXISTS num_bultos INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_service BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_pack BOOLEAN NOT NULL DEFAULT FALSE;
